// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 13 May 2025 22:07:06 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "include/picasso.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

