// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 15 May 2025 12:20:20 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "include/picasso.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

