// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 15 May 2025 12:20:20 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package picasso

/*
#include "include/picasso.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// _GnucStdcInline__ as defined in go/<predefined>:186
	_GnucStdcInline__ = 1
	// _NoInline__ as defined in go/<predefined>:290
	_NoInline__ = 1
)

// Status as declared in include/picasso.h:291
type Status int32

// Status enumeration from include/picasso.h:291
const (
	StatusSucceed           Status = C.STATUS_SUCCEED
	StatusOutOfMemory       Status = C.STATUS_OUT_OF_MEMORY
	StatusInvalidArgument   Status = C.STATUS_INVALID_ARGUMENT
	StatusNotSupport        Status = C.STATUS_NOT_SUPPORT
	StatusDeviceError       Status = C.STATUS_DEVICE_ERROR
	StatusMismatchingFormat Status = C.STATUS_MISMATCHING_FORMAT
	StatusUnknownError      Status = C.STATUS_UNKNOWN_ERROR
)

// ColorFormat as declared in include/picasso.h:435
type ColorFormat int32

// ColorFormat enumeration from include/picasso.h:435
const (
	ColorFormatRgba    ColorFormat = C.COLOR_FORMAT_RGBA
	ColorFormatArgb    ColorFormat = C.COLOR_FORMAT_ARGB
	ColorFormatAbgr    ColorFormat = C.COLOR_FORMAT_ABGR
	ColorFormatBgra    ColorFormat = C.COLOR_FORMAT_BGRA
	ColorFormatRgb     ColorFormat = C.COLOR_FORMAT_RGB
	ColorFormatBgr     ColorFormat = C.COLOR_FORMAT_BGR
	ColorFormatRgb565  ColorFormat = C.COLOR_FORMAT_RGB565
	ColorFormatRgb555  ColorFormat = C.COLOR_FORMAT_RGB555
	ColorFormatA8      ColorFormat = C.COLOR_FORMAT_A8
	ColorFormatUnknown ColorFormat = C.COLOR_FORMAT_UNKNOWN
)

// WrapType as declared in include/picasso.h:895
type WrapType int32

// WrapType enumeration from include/picasso.h:895
const (
	WrapTypeRepeat  WrapType = C.WRAP_TYPE_REPEAT
	WrapTypeReflect WrapType = C.WRAP_TYPE_REFLECT
)

// GradientSpread as declared in include/picasso.h:977
type GradientSpread int32

// GradientSpread enumeration from include/picasso.h:977
const (
	GradientSpreadPad     GradientSpread = C.GRADIENT_SPREAD_PAD
	GradientSpreadRepeat  GradientSpread = C.GRADIENT_SPREAD_REPEAT
	GradientSpreadReflect GradientSpread = C.GRADIENT_SPREAD_REFLECT
)

// LineCap as declared in include/picasso.h:1282
type LineCap int32

// LineCap enumeration from include/picasso.h:1282
const (
	LineCapButt   LineCap = C.LINE_CAP_BUTT
	LineCapRound  LineCap = C.LINE_CAP_ROUND
	LineCapSquare LineCap = C.LINE_CAP_SQUARE
)

// LineJoin as declared in include/picasso.h:1320
type LineJoin int32

// LineJoin enumeration from include/picasso.h:1320
const (
	LineJoinMiter       LineJoin = C.LINE_JOIN_MITER
	LineJoinMiterRevert LineJoin = C.LINE_JOIN_MITER_REVERT
	LineJoinMiterRound  LineJoin = C.LINE_JOIN_MITER_ROUND
	LineJoinRound       LineJoin = C.LINE_JOIN_ROUND
	LineJoinBevel       LineJoin = C.LINE_JOIN_BEVEL
)

// LineInnerJoin as declared in include/picasso.h:1354
type LineInnerJoin int32

// LineInnerJoin enumeration from include/picasso.h:1354
const (
	LineInnerMiter LineInnerJoin = C.LINE_INNER_MITER
	LineInnerBevel LineInnerJoin = C.LINE_INNER_BEVEL
	LineInnerJag   LineInnerJoin = C.LINE_INNER_JAG
	LineInnerRound LineInnerJoin = C.LINE_INNER_ROUND
)

// Composite as declared in include/picasso.h:1613
type Composite int32

// Composite enumeration from include/picasso.h:1613
const (
	CompositeClear       Composite = C.COMPOSITE_CLEAR
	CompositeSrc         Composite = C.COMPOSITE_SRC
	CompositeSrcOver     Composite = C.COMPOSITE_SRC_OVER
	CompositeSrcIn       Composite = C.COMPOSITE_SRC_IN
	CompositeSrcOut      Composite = C.COMPOSITE_SRC_OUT
	CompositeSrcAtop     Composite = C.COMPOSITE_SRC_ATOP
	CompositeDst         Composite = C.COMPOSITE_DST
	CompositeDstOver     Composite = C.COMPOSITE_DST_OVER
	CompositeDstIn       Composite = C.COMPOSITE_DST_IN
	CompositeDstOut      Composite = C.COMPOSITE_DST_OUT
	CompositeDstAtop     Composite = C.COMPOSITE_DST_ATOP
	CompositeXor         Composite = C.COMPOSITE_XOR
	CompositeDarken      Composite = C.COMPOSITE_DARKEN
	CompositeLighten     Composite = C.COMPOSITE_LIGHTEN
	CompositeOverlay     Composite = C.COMPOSITE_OVERLAY
	CompositeScreen      Composite = C.COMPOSITE_SCREEN
	CompositeMultiply    Composite = C.COMPOSITE_MULTIPLY
	CompositePlus        Composite = C.COMPOSITE_PLUS
	CompositeMinus       Composite = C.COMPOSITE_MINUS
	CompositeExclusion   Composite = C.COMPOSITE_EXCLUSION
	CompositeDifference  Composite = C.COMPOSITE_DIFFERENCE
	CompositeSoftlight   Composite = C.COMPOSITE_SOFTLIGHT
	CompositeHardlight   Composite = C.COMPOSITE_HARDLIGHT
	CompositeBurn        Composite = C.COMPOSITE_BURN
	CompositeDodge       Composite = C.COMPOSITE_DODGE
	CompositeContrast    Composite = C.COMPOSITE_CONTRAST
	CompositeInvert      Composite = C.COMPOSITE_INVERT
	CompositeInvertBlend Composite = C.COMPOSITE_INVERT_BLEND
	CompositeHue         Composite = C.COMPOSITE_HUE
	CompositeSaturation  Composite = C.COMPOSITE_SATURATION
	CompositeColor       Composite = C.COMPOSITE_COLOR
	CompositeLuminosity  Composite = C.COMPOSITE_LUMINOSITY
	CompositeError       Composite = C.COMPOSITE_ERROR
)

// Filter as declared in include/picasso.h:1659
type Filter int32

// Filter enumeration from include/picasso.h:1659
const (
	FilterNearest  Filter = C.FILTER_NEAREST
	FilterBilinear Filter = C.FILTER_BILINEAR
	FilterGaussian Filter = C.FILTER_GAUSSIAN
	FilterBicubic  Filter = C.FILTER_BICUBIC
	FilterQuadric  Filter = C.FILTER_QUADRIC
	FilterUnknown  Filter = C.FILTER_UNKNOWN
)

// FillRule as declared in include/picasso.h:1693
type FillRule int32

// FillRule enumeration from include/picasso.h:1693
const (
	FillRuleWinding FillRule = C.FILL_RULE_WINDING
	FillRuleEvenOdd FillRule = C.FILL_RULE_EVEN_ODD
	FillRuleError   FillRule = C.FILL_RULE_ERROR
)

// Charset as declared in include/picasso.h:1966
type Charset int32

// Charset enumeration from include/picasso.h:1966
const (
	CharsetAnsi    Charset = C.CHARSET_ANSI
	CharsetUnicode Charset = C.CHARSET_UNICODE
)

// FontWeight as declared in include/picasso.h:1988
type FontWeight int32

// FontWeight enumeration from include/picasso.h:1988
const (
	FontWeightRegular FontWeight = C.FONT_WEIGHT_REGULAR
	FontWeightMedium  FontWeight = C.FONT_WEIGHT_MEDIUM
	FontWeightBold    FontWeight = C.FONT_WEIGHT_BOLD
	FontWeightHeavy   FontWeight = C.FONT_WEIGHT_HEAVY
)

// TextType as declared in include/picasso.h:2201
type TextType int32

// TextType enumeration from include/picasso.h:2201
const (
	TextTypeSmooth TextType = C.TEXT_TYPE_SMOOTH
	TextTypeMono   TextType = C.TEXT_TYPE_MONO
	TextTypeStroke TextType = C.TEXT_TYPE_STROKE
)

// DrawTextType as declared in include/picasso.h:2353
type DrawTextType int32

// DrawTextType enumeration from include/picasso.h:2353
const (
	DrawTextFill   DrawTextType = C.DRAW_TEXT_FILL
	DrawTextStroke DrawTextType = C.DRAW_TEXT_STROKE
	DrawTextBoth   DrawTextType = C.DRAW_TEXT_BOTH
)

// TextAlign as declared in include/picasso.h:2379
type TextAlign int32

// TextAlign enumeration from include/picasso.h:2379
const (
	TextAlignCenter TextAlign = C.TEXT_ALIGN_CENTER
	TextAlignTop    TextAlign = C.TEXT_ALIGN_TOP
	TextAlignBottom TextAlign = C.TEXT_ALIGN_BOTTOM
	TextAlignLeft   TextAlign = C.TEXT_ALIGN_LEFT
	TextAlignRight  TextAlign = C.TEXT_ALIGN_RIGHT
)

// PathCmd as declared in include/picasso.h:3364
type PathCmd int32

// PathCmd enumeration from include/picasso.h:3364
const (
	PathCmdStop    PathCmd = C.PATH_CMD_STOP
	PathCmdMoveTo  PathCmd = C.PATH_CMD_MOVE_TO
	PathCmdLineTo  PathCmd = C.PATH_CMD_LINE_TO
	PathCmdCurve3  PathCmd = C.PATH_CMD_CURVE3
	PathCmdCurve4  PathCmd = C.PATH_CMD_CURVE4
	PathCmdEndPoly PathCmd = C.PATH_CMD_END_POLY
)

// PathOperation as declared in include/picasso.h:3532
type PathOperation int32

// PathOperation enumeration from include/picasso.h:3532
const (
	PathOpUnion     PathOperation = C.PATH_OP_UNION
	PathOpIntersect PathOperation = C.PATH_OP_INTERSECT
	PathOpXor       PathOperation = C.PATH_OP_XOR
	PathOpDiff      PathOperation = C.PATH_OP_DIFF
)
