// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 13 May 2025 22:07:06 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package picasso

/*
#include "include/picasso.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// Bool type as declared in include/picasso.h:60
type Bool int32

// Uchar16 type as declared in include/picasso.h:81
type Uchar16 uint16

// Schar16 type as declared in include/picasso.h:88
type Schar16 int16

// Context as declared in include/picasso.h:109
type Context C.ps_context

// Canvas as declared in include/picasso.h:116
type Canvas C.ps_canvas

// Image as declared in include/picasso.h:123
type Image C.ps_image

// Pattern as declared in include/picasso.h:130
type Pattern C.ps_pattern

// Gradient as declared in include/picasso.h:137
type Gradient C.ps_gradient

// Matrix as declared in include/picasso.h:144
type Matrix C.ps_matrix

// Path as declared in include/picasso.h:151
type Path C.ps_path

// Mask as declared in include/picasso.h:158
type Mask C.ps_mask

// Font as declared in include/picasso.h:165
type Font C.ps_font

// Glyph as declared in include/picasso.h:173
type Glyph struct {
	Glyph          unsafe.Pointer
	ref84be1ec8    *C.ps_glyph
	allocs84be1ec8 interface{}
}

// Size as declared in include/picasso.h:183
type Size struct {
	W              float32
	H              float32
	ref9075d356    *C.ps_size
	allocs9075d356 interface{}
}

// Rect as declared in include/picasso.h:197
type Rect struct {
	X              float32
	Y              float32
	W              float32
	H              float32
	refd063c4bd    *C.ps_rect
	allocsd063c4bd interface{}
}

// Point as declared in include/picasso.h:207
type Point struct {
	X              float32
	Y              float32
	ref98ad3a54    *C.ps_point
	allocs98ad3a54 interface{}
}

// Color as declared in include/picasso.h:221
type Color struct {
	R              float32
	G              float32
	B              float32
	A              float32
	ref495e8199    *C.ps_color
	allocs495e8199 interface{}
}

// FontInfo as declared in include/picasso.h:2147
type FontInfo struct {
	Size           float32
	Ascent         float32
	Descent        float32
	Leading        float32
	Unitsem        uint32
	ref4d462aab    *C.ps_font_info
	allocs4d462aab interface{}
}
