/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

 #pragma once

 #define THORVG_CAPI_BINDING_SUPPORT 1
 
 #define THORVG_FILE_IO_SUPPORT 1
 
 #define THORVG_GIF_SAVER_SUPPORT 1
 
 #define THORVG_LOTTIE_EXPRESSIONS_SUPPORT 1
 
 #define THORVG_LOTTIE_LOADER_SUPPORT 1
 
 #define THORVG_SVG_LOADER_SUPPORT 1
 
 #define THORVG_SW_RASTER_SUPPORT 1
 
 #define THORVG_THREAD_SUPPORT 1
 
 #define THORVG_TTF_LOADER_SUPPORT 1
 
 #define THORVG_VERSION_STRING "1.0.0"
 
 #define WIN32_LEAN_AND_MEAN 1
 
 